### ISSUE TITLE
Error: channel closed

### ISSUE THREAD

**Issue by mynane** [supabase/edge-runtime#103]
# Bug report

- [ ] I confirm this is a bug with Supabase, not with my own application. 
- [ ] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## Describe the bug

![image](https://github.com/supabase/edge-runtime/assets/9946926/72364b52-2632-4b26-9870-44a0bdf7228a)

```
ab -n 5000 -c 100 http://localhost:9000/empty-response
```

```
serving the request with ./examples/empty-response
Error: channel closed
    at async Function.create (ext:sb_user_workers/user_workers.js:80:21)
    at async createWorker (file:///Users/shijinhua/Documents/privatespace/Bun/github.com/mivim-runtime/runtime/examples/main/index.ts:33:16)
    at async callWorker (file:///Users/shijinhua/Documents/privatespace/Bun/github.com/mivim-runtime/runtime/examples/main/index.ts:48:28)
serving the request with ./examples/empty-response

```

Any other request will report an error after reporting an error

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1.  `const workerTimeoutMs = 1 * 1000`
2.  cargo run -- start
3.  ab -n 5000 -c 100 http://localhost:9000/empty-response

## Screenshots

![image](https://github.com/supabase/edge-runtime/assets/9946926/ff2f4e2e-b0dd-4736-8f55-e47c8e1f058f)
![image](https://github.com/supabase/edge-runtime/assets/9946926/bf1cc9f5-d762-4067-8e19-eb05a6c85046)

## System information

- OS: macOS
- Browser (if applies)  command line
- Version of none
- Version of Node.js: none

**Comment by mynane** [comment]
This issue should be the destruction of the runtime after a timeout. During this process, there are also requests coming in to handle exceptions and report errors. Is it possible to reset the timeout before each request

**Comment by marc-tech** [comment]
same error here when i use openai to fetch and pipe the response stream in local
