### ISSUE TITLE
ReferenceError: DOMException is not defined

### ISSUE THREAD

**Issue by 1fexd** [supabase/edge-runtime#113]
# Bug report

- [x] I confirm this is a bug with Supabase, not with my own application. 
- [x] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## Describe the bug

I am trying to use the `deno_dom` package but it fails with an exception:

```
ReferenceError: DOMException is not defined
    at default (https://deno.land/x/deno_dom@v0.1.38/src/dom/selectors/nwsapi.js:20:9)
    at HTMLDocument.get _nwapi (https://deno.land/x/deno_dom@v0.1.38/src/dom/document.ts:81:65)
    at HTMLDocument.querySelector (https://deno.land/x/deno_dom@v0.1.38/src/dom/document.ts:184:21)
    at Server.<anonymous> (file:///home/deno/functions/test/index.ts:5:27)
    at Server.#respond (https://deno.land/std@0.168.0/http/server.ts:221:43)
    at Server.#serveHttp (https://deno.land/std@0.168.0/http/server.ts:258:26)
```

It works fine when I run my function with `deno run`

## To Reproduce

* Make sure the supabase stack is running
* Create the following function

```
import { serve } from "https://deno.land/std@0.168.0/http/server.ts"
import { DOMParser, } from "https://deno.land/x/deno_dom/deno-dom-wasm.ts";

serve(async (req) => {
    const document = new DOMParser().parseFromString("<html></html>", "text/html");
    const html = document.querySelector("html");

    return new Response();
});
```
* Serve your functions locally
* Send request to function via curl

**Comment by andreespirela** [comment]
Can't reproduce.

```
console.log(html)
```

<img width="494" alt="image" src="https://github.com/supabase/edge-runtime/assets/60560109/ef35a011-a134-4d59-8399-62021414b165">

Also, doing a return response with `hello world`

<img width="973" alt="image" src="https://github.com/supabase/edge-runtime/assets/60560109/c034c5da-ac51-40bc-a164-e650d67e8f6e">


<img width="387" alt="image" src="https://github.com/supabase/edge-runtime/assets/60560109/6fd18cb3-a1d2-49af-a90f-71cbe0f8a404">


Version: Latest main

cc @laktek

**Comment by laktek** [comment]
@1fexd Which version of the Supabase CLI are you using? Can you try upgrading to the latest?

**Comment by 1fexd** [comment]
Oh, my bad, should've thought of that myself 🤦‍♂️. Was using `1.41.4` and upgraded to `1.64.8` and now it works fine. Sadly supabase doesn't seem to provide a real apt repository instead of just `deb` packages so there is no auto-update :(
