### ISSUE TITLE
Edge function does not execute in parallel

### ISSUE THREAD

**Issue by candymandev** [supabase/edge-runtime#121]
I have an edge function `generate-image`. When I invoke the function locally many times, each invocation runs in parallel as I expect.

![local](https://user-images.githubusercontent.com/94403944/173210070-dab51903-123a-40fa-b67e-4a4598731e2f.png)

When I deploy the function to production with the same code to invoke it many times, it seems to run sequentially. Something on the server side seems to be limiting the function to run only one execution at a time.

![production](https://user-images.githubusercontent.com/94403944/173210091-9b968ed8-4ae1-4bd1-ad37-f8f857718665.png)

According to the function metrics in Supabase, the function executes in less than a second. The duration of the invocations is pretty consistent. So it seems that although the HTTP requests are initiated properly, something on the server side is causing each subsequent invocation to start only when the last one completes.

![screenshot-2022-06-11-21-12-25](https://user-images.githubusercontent.com/94403944/173210246-d2d37ef3-9bf2-4cea-9972-6f4c63951362.png)

My expectation is that these functions would run completely in parallel up to the limits of my pro plan. Having these functions run sequentially misses out on one of the biggest benefits of serverless edge functions in my opinion. Is this a limitation of my plan? Is there a way to improve the performance of my function?

**Comment by laktek** [comment]
@ChuckJonas Thanks for reporting it! Transferring to edge-runtime repo to further investigate.

**Comment by AndryHTC** [comment]
I'm using version 1.5.5, and functions are not being executed in parallel. Only the first one is processed, while the others remain pending. If not executed within a few seconds, they receive a 503 error. The following log appears in the function serve CLI
```
InvalidWorkerCreation: worker did not respond in time
    at async UserWorker.create (ext:sb_user_workers/user_workers.js:144:15)
    at async Object.handler (file:///root/index.ts:147:22)
    at async respond (ext:sb_core_main_js/js/http.js:163:14) {
  name: "InvalidWorkerCreation"
}
```

**Comment by tipo122** [comment]
I encountered the same issue, but it was resolved by changing the policy in config.toml under [edge_runtime] from oneshot to per_worker. It worked for me after that.

```
[edge_runtime]
policy = "per_worker"
```
