### ISSUE TITLE
Add support for DENO_CERT env variable

### ISSUE THREAD

**Issue by laktek** [supabase/edge-runtime#137]
We need to make sure if a user provides a custom certificate via DENO_CERT env variable, it's applied to the user function.

**Comment by laktek** [comment]
Closing this since this is better handled on the user function (eg. provide the certs to postgress client library).

**Comment by Thrimbda** [comment]
do we have some document pointing out how to provide a self-signed cert when filing an HTTP request from Edge Functions?

**Comment by AriFordsham** [comment]
I'm behind a MITM proxy, and I can't run `supabase start` locally because it seems DENO_CERT is not passed through from .env to the Deno runtime.
