### ISSUE TITLE
Worker thread cannot be created

### ISSUE THREAD

**Issue by SorenMG** [supabase/edge-runtime#159]
# Bug report

- [ x ] I confirm this is a bug with Supabase, not with my own application. 
- [ x ] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## Describe the bug

Running supabase docker instance 'edge-runtime:v1.6.6' docker container, using `supabase functions serve` results in the error:
`Operation not permitted (os error 1)
CPU time used: 0ms
InvalidWorkerCreation: worker boot error
    at async Function.create (ext:sb_user_workers/user_workers.js:84:15)
    at async Server.<anonymous> (file:///home/deno/main/index.ts:110:24)
    at async Server.#respond (https://deno.land/std@0.182.0/http/server.ts:220:24)`

After further investigation, it seems it is this line `const key = await core.opAsync('op_user_worker_create', readyOptions);` in `/crates/sb_workers/user_workers.js` creating the issue.

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Install edge-runtime:v1.6.6 (also replicated on v1.8.1)
2. Run `supabase functions serve`
3. Call a function

This is my function:
`import { serve } from "https://deno.land/std@0.168.0/http/server.ts"

serve(() => {
  return new Response()
})`

## Expected behavior

Edge function should be executed

## System information

- OS: macOS M1
- Supabase CLI: 1.83.7
- Docker version: v.4.22.0

**Comment by laktek** [comment]
@SorenMG Can you share your `main/index.ts`? Have you made any modifications to it?

**Comment by SorenMG** [comment]
Hey Iaktek, issue got resolved after running the edge function again. Have not been working for +1 month and have no idea what I did differently. Apologies for wasting your time :-)

**Comment by laktek** [comment]
No worries! good to heat the issue was resolved.
