### ISSUE TITLE
forceCreate does not clean up isolates after they are created

### ISSUE THREAD

**Issue by meyer9** [supabase/edge-runtime#192]
# Bug report

- [x] I confirm this is a bug with Supabase, not with my own application. 
- [x] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

### Describe the bug

Edge runtime always crashes after a few minutes of development. This is a huge blocker to using Supabase edge functions locally.

I've tried to gather all of the information I can, but I'm not super familiar with Rust async code.

I'm on an M2 MacBook Pro running edge-runtime through Docker.

## To Reproduce

1. Run this basic Oak server code with `supabase functions server --debug`:

```typescript
import { Application } from 'oak';
const app = new Application();
app.use((ctx) => {
  ctx.response.body = 'Hello world!';
});
await app.listen({ port: 8000 });
```

2. Send a request
3. Notice how edge-runtime times out and prints error logs instead of exiting gracefully
4. Using `autocannon` load testing tool: `autocannon -c 20 -d 60 localhost:54321/functions/v1/api/lol`
5. Notice how edge-runtime runs out of memory and crashes

## Expected behavior

Using Oak should exit gracefully after serving a request instead of timing out to free up resources. Or maybe reuse the isolate for other requests?

## System information

- OS: macOS 14.0 (13-inch, M2, 2022)
- Version of supabase-js: beta (1.102.2)
- Version of Node.js: v20.5.0

### Isolates never seem to be terminated

For every request, I see the following 5 log lines. From what I can tell, these mean that the isolate is timing out after a few seconds of CPU time/wall clock time. Shouldn't these only handle one request and then exit?

```
# oak server is timing out
# this happens for every request before eventually crashing
wall clock duration reached. isolate: 6e4779a6-4a69-499d-81d3-8af6e727464d
event loop error: Uncaught Error: execution terminated
DEBUG failed to send cpu alarm to the provided channel
DEBUG CPU time used: 160ms
DEBUG Sending warning alert CloseNotify
```

Also, I saw this strange case where the CPU time was negative. Maybe this is a hint at the underlying problem:
```
wall clock duration reached. isolate: 2dd53cc0-b8cd-4437-974c-c09313dec8ad
DEBUG failed to send cpu alarm to the provided channel
DEBUG CPU time used: -662ms
```

### Memory leak

I'm fairly sure this would cause a memory leak with many requests at the same time. I tried this command with the above code and saw a huge spike in memory and eventually a crash due to Docker killing the container:

```
autocannon -c 20 -d 60 localhost:54321/functions/v1/api/lol
```

Result:
```
Req/Bytes counts sampled once per second.
# of samples: 60

339 2xx responses, 4915 non 2xx responses
5k requests in 60.08s, 1.53 MB read
89 errors (74 timeouts)
```

CPU/Memory graph (only two samples as the test was starting since it crashed soon after):

<img width="1154" alt="SCR-20231014-qdhm" src="https://github.com/supabase/edge-runtime/assets/1247379/8e1a5493-9837-4abf-ba40-59787412d71f">

**Comment by meyer9** [comment]
Switching `forceCreate` to false switches the issue. Maybe that should be the default here? Or at least configurable?

https://github.com/supabase/cli/blob/8d30ba2337fbd7ff4b892b97c625784b6c6487a9/internal/functions/serve/templates/main.ts#L129

**Comment by meyer9** [comment]
I opened an PR on the CLI repo to track this - looks like it's a problem with the CLI's main worker code: https://github.com/supabase/cli/pull/1579

**Comment by meyer9** [comment]
I'm going to reopen this issue because I think disabling `forceCreate` breaks auto reload. Seems like we want to force a new worker if any of the files have changed? Hot reloading by creating a runtime for each request doesn't seem like the most efficient solution.

**Comment by meyer9** [comment]
Here's another example after basic usage of `supabase functions serve`:

<img width="1152" alt="image" src="https://github.com/supabase/edge-runtime/assets/1247379/bb3484b2-4ca9-4ce3-b20a-62a0884ebb26">

It started failing to respond and eventually crashed.

**Comment by laktek** [comment]
@meyer9 Was all the examples with Oak? Do you experience similar issues if you use deno's default HTTP library too?

**Comment by meyer9** [comment]
> Was all the examples with Oak? Do you experience similar issues if you use deno's default HTTP library too?

I thought it could be related, but it seems to also happen with Deno's HTTP library. The problem is less pronounced with Deno's library probably because it needs to download/load less from disk + network per worker when using the standard library.

With 200 requests with a plain Deno server, I see the memory spike to 2 GB and slowly decrease as workers are freed up.
