### ISSUE TITLE
`console.log(req)` in worker context triggers SIGSEGV after v1.21.1

### ISSUE THREAD

**Issue by nyannyacha** [supabase/edge-runtime#199]
# Bug report

- [x] I confirm this is a bug with Supabase, not with my own application. 
- [x] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## Describe the bug

Deploying edge-runtime image after v1.21.1 in the docker, `SIGSEGV` is triggered when executing a line that invokes `console.log` with a request.

## To Reproduce

1. Deploy edge-runtime image `1.22.3` into the docker.
2. Write a simple function invoking `console.log(req)` in the serve callback.
3. Send a request to the function.
4. `SIGSEGV` triggered in `edge-runtime` and the process dies.

## Expected behavior

`edge-runtime` should not be killed due `console.log(req)` and `SIGSEGV` should not be triggered.

## Screenshots

<img width="1008" alt="1" src="https://github.com/supabase/edge-runtime/assets/46702285/6cfdd2ce-b5bc-48b6-acc5-7a01c8d74e99">
<img width="1006" alt="2" src="https://github.com/supabase/edge-runtime/assets/46702285/5a1cd6f3-27a4-447a-a964-7fd496e644f2">

## System information

- Host OS: Ubuntu (Linux vultr 5.15.0-84-generic 93-Ubuntu SMP Tue Sep 5 17:16:10 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux)

- Docker Version: 24.0.6, build ed223bc

## Additional context

I have only tested v1.21.1 and v1.22.3 because other versions were not available on dockerhub.

**Comment by chatch** [comment]
I'm also seeing this error with edge-runtime v1.22.3. 

Ubuntu: 20.04.1 (kernel: 5.15.0-88-generic)
Docker: 24.0.7

**Comment by nyannyacha** [comment]
This problem might be related to the upstream. It seems SIGSEGV has triggered while allocating JIT memory space. `v8::internal::ThreadIsolation::RegisterJitAllocation`

Below is the crashed frame on the debug build
```
Process 4198 launched: '/usr/local/bin/edge-runtime' (x86_64)
Snapshot already up to date. Skipping pending resolution.
Listening on http://localhost:9999/
Snapshot already up to date. Skipping pending resolution.
Process 4198 stopped
* thread #10, name = 'sb-iso-79f87fce', stop reason = unknown crash reason
    frame #0: 0x000055555aeb6703 edge-runtime`v8::internal::ThreadIsolation::RegisterJitAllocation(unsigned long, unsigned long, v8::internal::ThreadIsolation::JitAllocationType) at code-memory-access.cc:435:10
```

So... I can be confirmed no more SIGSEGV is triggered if I disable the V8 JIT compilation(--jitless) on the main branch build. Still, it is not a usable option in production due to it making execution speed slow significantly.
