### ISSUE TITLE
supabase serve uses "--no-npm" mode for Deno. Why? This breaks code that needs npm modules.

### ISSUE THREAD

**Issue by evelant** [supabase/edge-runtime#211]
# Bug report

## Describe the bug

I ported my firebase functions to supabase edge functions. In doing so I had to use some npm modules, which I thought was fine since deno supports npm. Upon trying to run my code however I was suprised to be hit with 

```
worker thread panicked Unsupported scheme "npm" for module "npm:/@effect/io@0.7.0/Exit". Supported schemes: [
    "data",
    "blob",
    "file",
    "http",
    "https",
]
```

The supabase cli passes "--no-npm" when invoking Deno. 

Code is here https://github.com/supabase/cli/blob/a30210717bdb1f3c9d3d5ce940d000971fc1a6da/internal/functions/serve/serve.go#L190

As far as I can tell this isn't documented anywhere by Supabase resulting in a surprise for users. Since Supabase targets people who want to switch from Firebase this is likely to affect almost everyone who attempts to switch as most people use npm modules in their firebase functions.

## To Reproduce

1. Add an npm specifier to your import_map.json such as `"@effect/io/": "npm:/@effect/io@0.7.0/",`
2. run `supabase functions serve`
3. Observe that function crashes at runtime due to `--no-npm` option passed to Deno by supabase cli.

## Expected behavior

All Deno features should work. If there's a specific reason why `--no-npm` is needed it should be clearly documented along with an explanation of how to work around being unable to use npm import specifiers.

## Screenshots

N/A

## System information

- OS: macOS
- Browser N/A
- Version of supabase-js: N/A
- Version of Node.js: N/A

**Comment by evelant** [comment]
@laktek Any timeline on when npm specifiers might get supported in the edge runtime? 

I'm still stuck without any type checking in editor for edge functions because of multiple bugs with vscode_deno (see https://github.com/supabase/cli/issues/1303#issuecomment-1804090915). Working with edge functions is so painful because of Deno. Npm support might help alleviate that since esm.sh doesn't work well with a lot of packages.

**Comment by joshpachner** [comment]
I would also love for npm support.
Or for documentation of how to get around it for certain use cases (we're trying to get Drizzle up and running on the edge functions (so that we can have type help on the edge), and the documentation of using drizzle in deno is literally garbage (true its not supabase's fault))

**Comment by zes** [comment]
Deno deploy now support npm packages 👀

**Comment by laktek** [comment]
edge-runtime now supports npm modules https://supabase.com/blog/edge-functions-node-npm
