### ISSUE TITLE
"An arrow function is not allowed here" on valid TS code

### ISSUE THREAD

**Issue by evelant** [supabase/edge-runtime#214]
# Bug report

- [ X ] I confirm this is a bug with Supabase, not with my own application. 
- [ X ] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## Describe the bug

With a valid typescript function the edge runtime fails with `An arrow function is not allowed here`

## To Reproduce

The following function will trigger the issue, from https://github.com/Effect-TS/effect/blob/f0a4bf430c0d723e4d6e3f3fb48dcc7118338653/src/MutableHashSet.ts#L82-L88

```ts
export const add: {
    <V>(key: V): (self: MutableHashSet<V>) => MutableHashSet<V>
    <V>(self: MutableHashSet<V>, key: V): MutableHashSet<V>
} = Dual.dual<
    <V>(key: V) => (self: MutableHashSet<V>) => MutableHashSet<V>,
    <V>(self: MutableHashSet<V>, key: V) => MutableHashSet<V>
>(2, (self, key) => (MutableHashMap.set(self.keyMap, key, true), self))
```

## Expected behavior

Valid typescript code should run

## Screenshots

N/A

## System information

- OS: macOS
- Browser (if applies) N/A
- Version of edge-runtime: 1.22.4
- Version of Node.js: N/A

## Additional context

Looks like there was an old issue in `swc` that was resolved. Is edge-runtime using a very old version of swc? https://github.com/swc-project/swc/issues/5077

**Comment by nyannyacha** [comment]
Hi! @evelant 😋

Well... I tried to bisect on SWC playground using a code that appeared in the issue that you linked above.
But it seems the parsing issue appears even at the nightly build 🤔

Check look this out:
SWC 1.33.2: [Playground](https://play.swc.rs/?version=1.3.22&code=H4sIAAAAAAAAAwsoys%2FNLE7VS8zJsbEJsdPQVLC1UyjLz0yx04iO1bQGAG6eJC4fAAAA&config=H4sIAAAAAAAAA1VPOw7DIAzdOQXy3KFi6NA79BCIOhERAYQdqSjK3QsJpM1mv4%2Ff8yqkhIkMPOVaxrJEnQjTuReEsmf9KQhwjkgm2chw6yxTpQbtCHdoOxhgnUbk6kJSd6WaA1wIhN3RsNl6O%2BT%2FTBPmmJDoKqxS7UeH10TRUmEO72Un2y%2B179HgAT9RDzsPg6VXd3JaUGxfBMLf3xcBAAA%3D)
SWC 1.3.102-nightly-20231219: [Playground](https://play.swc.rs/?version=1.3.102-nightly-20231219.1&code=H4sIAAAAAAAAAwsoys%2FNLE7VS8zJsbEJsdPQVLC1UyjLz0yx04iO1bQGAG6eJC4fAAAA&config=H4sIAAAAAAAAA1VPOw7DIAzdOQXy3KFi6NA79BCIOhERAYQdqSjK3QsJpM1mv4%2Ff8yqkhIkMPOVaxrJEnQjTuReEsmf9KQhwjkgm2chw6yxTpQbtCHdoOxhgnUbk6kJSd6WaA1wIhN3RsNl6O%2BT%2FTBPmmJDoKqxS7UeH10TRUmEO72Un2y%2B179HgAT9RDzsPg6VXd3JaUGxfBMLf3xcBAAA%3D)
Typescript v5.3.2: [Playground](https://www.typescriptlang.org/play?ts=5.3.2#code/AoJw9gtglgzgpgOgIYBsUB50BUB8AKASgAIBeHIgNzCgBN8BtAXQIG4g)
Typescript v4.9.5: [Playground](https://www.typescriptlang.org/play?ts=4.9.5#code/AoJw9gtglgzgpgOgIYBsUB50BUB8AKASgAIBeHIgNzCgBN8BtAXQIG4g)
Typescript nightly: [Playground](https://www.typescriptlang.org/play?ts=5.4.0-dev.20231219#code/AoJw9gtglgzgpgOgIYBsUB50BUB8AKASgAIBeHIgNzCgBN8BtAXQIG4g)

**Comment by nyannyacha** [comment]
Note: The presence or absence of newlines seems to determine the success of parsing... even so far the latest version.

```typescript
dual<<V>(key: V) => V>(2) // NOK

// OK
dual<
   <V>(key: V) => V>(2)
```

**Comment by nyannyacha** [comment]
Hey @evelant, this looks like an upstream issue, can you close it?

**Comment by nyannyacha** [comment]
I will be submitting this issue upstream 😁

**Comment by nyannyacha** [comment]
The upstream issue is [#8581](https://github.com/swc-project/swc/issues/8581) 😄

**Comment by evelant** [comment]
Sorry for not getting back to you! I switched away from supabase edge-runtime (in favor of Bun on fly.io because of so many Deno specific problems) so this fell off my radar.
