### ISSUE TITLE
Support jsxImportSource 

### ISSUE THREAD

**Issue by mcandeia** [supabase/edge-runtime#233]
# Chore

## Describe the chore

Currently deno supports jsxImportSource via deno.json, https://docs.deno.com/runtime/manual/advanced/jsx_dom/jsx

is there a way to support the same passing as parameter of createworker?

**Comment by mcandeia** [comment]
hey @andreespirela is there a way to get it running quickly? where I need to change to force a specific jsxImportSource?

**Comment by mcandeia** [comment]
Hey @nyannyacha, can you help us? We have an entire company (https://deco.cx) waiting for this. so this can unblock running https://github.com/denoland/fresh sites.

**Comment by mcandeia** [comment]
Perhaps @laktek 👀 can you provide some guidance? I’m not a pro rust programmer but I think would be a good first issue

**Comment by andreespirela** [comment]
@mcandeia Hey there! Will be taking care of this this week.

**Comment by mcandeia** [comment]
Amazing @andreespirela, please let me know if you have any progress on this, can be a WIP. We are planning to have a launch of our new product version on April 1st and would be amazing to have edge-runtime running our sites, don't hesitate to reach me out if needed

https://deco.day/

**Comment by mcandeia** [comment]
Hey @andreespirela any progress on this? Looking forward to see it running fresh sites

**Comment by mcandeia** [comment]
Just to let you know, I managed to have it working with an old version of this repository. But when I tried to apply my changes in the latest versions it did not work. looks a regression for me, I'm receiving a "Path not found" for a dependency that is required,

<img width="1092" alt="image" src="https://github.com/supabase/edge-runtime/assets/5839364/3fb6b6c1-bc66-4878-8fcd-6c3137a5e693">

To reproduce just clone and run (./scripts/run.sh) the following PR
https://github.com/deco-cx/edge-runtime/pull/2/files

**Comment by nyannyacha** [comment]
> Just to let you know, I managed to have it working with an old version of this repository. But when I tried to apply my changes in the latest versions it did not work. looks a regression for me, I'm receiving a "Path not found" for a dependency that is required,

After looking at the call stack, this seems to be related to the static fs PR.

Note: https://github.com/supabase/edge-runtime/blob/5420f03cfcbe43f2f9f8ede435aec6d795c53c7f/crates/sb_fs/virtual_fs.rs#L438-L488

cc @andreespirela

**Comment by mcandeia** [comment]
> > Just to let you know, I managed to have it working with an old version of this repository. But when I tried to apply my changes in the latest versions it did not work. looks a regression for me, I'm receiving a "Path not found" for a dependency that is required,
> 
> Note:
> 
> https://github.com/supabase/edge-runtime/blob/5420f03cfcbe43f2f9f8ede435aec6d795c53c7f/crates/sb_fs/virtual_fs.rs#L438-L488
> 
> https://github.com/supabase/edge-runtime/blob/5420f03cfcbe43f2f9f8ede435aec6d795c53c7f/crates/sb_fs/static_fs.rs#L317-L322
> 
> cc @andreespirela

I'm trying to understand the overall architecture, will try to fix it. npm dependencies should be  fetched from vfs or static fs ? It looks like a symlink to me, maybe a hard instead of a soft ? Will check

**Comment by mcandeia** [comment]
I've removed the dependency of `@opentelemetry` then it starts to work again... except that the Web Worker interface is not available, I'm not sure if this is also a changed that happened in the latest releases of this code was't not being executed in my previous tests.

Error:
<img width="644" alt="image" src="https://github.com/supabase/edge-runtime/assets/5839364/2fd91619-4010-470e-99c4-21ec4b842f2c">

code: https://denopkg.com/deco-sites/std@1.22.0/utils/worker.ts

**Comment by mcandeia** [comment]
There's a lot of work to do, but I'm pretty confident that is possible to run fresh sites.

**Comment by andreespirela** [comment]
There's a PR out for this https://github.com/supabase/edge-runtime/pull/301 . Should be merged either today or tomorrow. Thanks for the wait

**Comment by mcandeia** [comment]
Awesome @andreespirela!!

How about the other problems I mentioned? Should I create a different issue for those or do you have any clue about that?

**Comment by andreespirela** [comment]
@mcandeia I believe it will be fixed with this PR

**Comment by mcandeia** [comment]
@andreespirela you mean the WebWorker error and the path not found? It seems unrelated to me, but I'll very happy if it fixes both problems.

**Comment by mcandeia** [comment]
Looking forward for it @andreespirela !
