### ISSUE TITLE
Get Deno version for edge runtime

### ISSUE THREAD

**Issue by bombillazo** [supabase/edge-runtime#236]
**Is your feature request related to a problem? Please describe.**

Currently, there is no clear way to know which version of Deno is running in our Edge runtime locally and remotely.

**Describe the solution you'd like**

Some CLI commands or ways to fetch the version of Deno currently being used.

**Describe alternatives you've considered**

N/A

**Comment by sweatybridge** [comment]
Moving this issue to edge runtime since the deno version is pinned by cargo at compile time.

**Comment by nyannyacha** [comment]
Yeah, It prints out just the runtime version without the deno version when running runtime binary with `-V` flag.

```
vscode ➜ /workspaces/edge-runtime $ ./target/debug/edge-runtime --help
A server based on Deno runtime, capable of running JavaScript, TypeScript, and WASM services

Usage: edge-runtime [OPTIONS] [COMMAND]

Commands:
  start     Start the server
  bundle    Creates an 'eszip' file that can be executed by the EdgeRuntime. Such file contains all the modules in contained in a single binary.
  unbundle  Unbundles an .eszip file into the specified directory
  help      Print this message or the help of the given subcommand(s)

Options:
  -v, --verbose     Use verbose output
  -q, --quiet       Do not print any log messages
      --log-source  Include source file and line in log messages
  -h, --help        Print help
  -V, --version     Print version
vscode ➜ /workspaces/edge-runtime $ ./target/debug/edge-runtime -V
edge-runtime 0.1.0
vscode ➜ /workspaces/edge-runtime $ 
```

**Comment by nyannyacha** [comment]
I quickly investigated this repository and the deno repository.

So... The version of deno depends on the [package version] of the deno command line crate, so I think there's no direct way to get the actual deno mainline version that runtime uses unless hardcode the version.

[package version]: https://github.com/denoland/deno/blob/main/cli/Cargo.toml

**Comment by nyannyacha** [comment]
How about printed out like this?

```
vscode ➜ /workspaces/edge-runtime $ ./target/debug/edge-runtime --version
edge-runtime 0.1.0
deno 1.37.2 (debug, aarch64-unknown-linux-gnu)
vscode ➜ /workspaces/edge-runtime $ ./target/debug/edge-runtime -V
edge-runtime 0.1.0
deno 1.37.2 (debug, aarch64-unknown-linux-gnu)
vscode ➜ /workspaces/edge-runtime $ 
```

**Comment by nyannyacha** [comment]
I will submit a PR about this.
But The maintenance guys said they were going on vacation. So it might take time for PR to arrive at the main branch.

**Comment by bombillazo** [comment]
Hey, out of curiosity, how will one be able to query this?

**Comment by nyannyacha** [comment]
Hi! @bombillazo 😁

> Hey, out of curiosity, how will one be able to query this?

If you are an end user of the supabase product, You might not need to care about this. If the runtime exposes the Deno version through the command line switch like this, Maybe... `@supabase/cli` would take this and relay this information to the user. 

But I don't know how `@supabase/cli` will take care. @sweatybridge  seems to be the maintainer of `@supabase/cli`, so maybe he has the plan 🤣

Sorry for the ambiguous answer 😞
I'm not a member of the supabase team so I don't have the visibility of overall situation.
