### ISSUE TITLE
Promise.withResolvers is undefined

### ISSUE THREAD

**Issue by haschu** [supabase/edge-runtime#239]
# Bug report

- [x] I confirm this is a bug with Supabase, not with my own application. 
- [x] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## Describe the bug

Currently, `Promise.withResolvers` is undefined on edge functions. Therefore, [mergeReadableStreams](https://deno.land/std@0.131.0/streams/merge.ts?s=mergeReadableStreams) also does not work and throws: 
```
[Error] TypeError: Promise.withResolvers is not a function
    at https://deno.land/std@0.211.0/streams/merge_readable_streams.ts:18:51
    at Array.map (<anonymous>)
    at mergeReadableStreams (https://deno.land/std@0.211.0/streams/merge_readable_streams.ts:18:35)
```

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Create a new edge function with `console.log(Promise.withResolvers);`
2. Call edge function and view logs that say `undefined`

## Expected behavior

`Promise.withResolvers` should be implemented.

## System information

- OS: macOS
- Version of supabase cli: 1.127.4
- Version of Node.js: v18.18.2

**Comment by haschu** [comment]
As a workaround, you can use an older version of deno/std when Promise.resolve was not yet implemented.

**Comment by nyannyacha** [comment]
Note: That feature was proposed on ES2023[^1] and started to ship from v8 11.9[^2]. Deno Upstream rolled up v8 11.7 to 12.0 a few weeks ago[^3], so it should be rolled up v8 version to bring in that feature.

--
[^1]: https://tc39.es/proposal-promise-with-resolvers/
[^2]: https://chromium-review.googlesource.com/c/v8/v8/+/4873333
[^3]: https://github.com/denoland/rusty_v8/pull/1361

**Comment by nyannyacha** [comment]
@andreespirela I think we can close this now.
