### ISSUE TITLE
ReferenceError: Status is not defined when using Hocuspocus NPM package

### ISSUE THREAD

**Issue by colin-chadwick** [supabase/edge-runtime#297]
# Bug report

- [x] I confirm this is a bug with Supabase, not with my own application. 
- [x] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## Describe the bug

When trying to use the Hocuspocus package with the Supabase edge runtime, the following error is thrown:

```bash
ReferenceError: Status is not defined
    at Server.<anonymous> (file:///home/deno/main/index.ts:164:13)
    at eventLoopTick (ext:core/01_core.js:64:7)
    at async #respond (https://deno.land/std@0.182.0/http/server.ts:220:18)
serving the request with /home/deno/functions/document-sync
runtime has escaped from the event loop unexpectedly: event loop error: TypeError: Deno.addSignalListener is not a function
    at process.on (node:process:345:14)
    at Hocuspocus.listen (file:///tmp/sb-compile-edge-runtime/node_modules/localhost/@hocuspocus/server/2.11.3/dist/hocuspocus-server.esm.js:2509:21)
    at file:///home/deno/functions/document-sync/index.ts:5:8
failed to send request to user worker: connection error: Connection reset by peer (os error 104)
user worker failed to respond: connection error: Connection reset by peer (os error 104)
InvalidWorkerResponse: user worker failed to respond
    at async Promise.allSettled (index 1)
    at async UserWorker.fetch (ext:sb_user_workers/user_workers.js:70:21)
    at async Server.<anonymous> (file:///home/deno/main/index.ts:146:12)
    at async #respond (https://deno.land/std@0.182.0/http/server.ts:220:18) {
  name: "InvalidWorkerResponse"
}
```

## To Reproduce

The function file:
```ts
import { Server } from 'npm:@hocuspocus/server@latest'

const server = Server.configure({
  port: 8000,
})

server.listen()

```

## Expected behavior

The function is working when using the `deno run` command of the Deno CLI, but fails on the Supabase edge runtime, both in the hosted and in the local environment.

**Comment by nyannyacha** [comment]
Note: https://github.com/ueberdosis/hocuspocus/blob/930a61c81e111cda2b692bf1d89b38bfce5d721d/packages/server/src/Hocuspocus.ts#L180-L182

**Comment by nyannyacha** [comment]
> event loop error: TypeError: Deno.addSignalListener is not a function

We probably shouldn't allow receiving Unix signals for user workers. But I think we could replace this with a mock.

**Comment by nyannyacha** [comment]
> ReferenceError: Status is not defined
    at Server.<anonymous> (file:///home/deno/main/index.ts:164:13)
    at eventLoopTick (ext:core/01_core.js:64:7)
    at async #respond (https://deno.land/std@0.182.0/http/server.ts:220:18)

Note: https://github.com/supabase/cli/blob/develop/internal/functions/serve/templates/main.ts#L174-L179

cc @laktek

**Comment by nyannyacha** [comment]
```typescript
// ./examples/hello-world/index.ts

import { Server } from 'npm:@hocuspocus/server@latest'

const server = Server.configure({
	port: 8000,
})

server.listen()
```

```
GET /hello-world HTTP/1.1
Transfer-Encoding: chunked
User-Agent: PostmanRuntime/7.37.0
Accept: */*
Cache-Control: no-cache
Postman-Token: 4eb4fe07-d4fc-43d7-adda-ee4d6765a5d7
Host: 127.0.0.1:9998
Connection: keep-alive
 
HTTP/1.1 200 OK
content-type: text/plain
vary: Accept-Encoding
content-length: 2
date: Mon, 25 Mar 2024 04:21:30 GMT
 
OK
```

Hey @colin-chadwick 😁
I've created a patch and tested it, that package seems to simply output `OK`.

Is this the expected output?

**Comment by colin-chadwick** [comment]
Hi @nyannyacha 👋 
Yes, that's the expected output. Nice job! I'll test if the websocket connection works as well, but I think it should.

**Comment by nyannyacha** [comment]
Hello @colin-chadwick 😁

I'm glad the output I showed you is what you expected.

However, if you are using the Supabase cloud (not self-hosted), my understanding is that websocket connections are not possible. (Note that I am not a member of the Superbase team)

If you are planning to do that, you will need to reach out to the team.

Have a good day!

**Comment by colin-chadwick** [comment]
Thanks for the follow up. I'm self hosting Supabase, so that. shouldn't be a problem.

Best, 
Colin

**Comment by nyannyacha** [comment]
Then you should be fine 😎
If you find any other issues, please don't hesitate to report us!
