### ISSUE TITLE
TypeError: upgradeHttpRaw may only be used with Deno.serve | Connecting to websocket provided by NPM package

### ISSUE THREAD

**Issue by colin-chadwick** [supabase/edge-runtime#300]
# Bug report

- [x] I confirm this is a bug with Supabase, not with my own application. 
- [x] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## Describe the bug

When trying to connect to the websocket provided by the [Hocuspocus](https://github.com/ueberdosis/hocuspocus) package with the Supabase edge runtime, the following error is thrown:

```bash
[Error] TypeError: upgradeHttpRaw may only be used with Deno.serve
      at upgradeHttpRaw (ext:deno_http/00_serve.js:119:9)
      at handler (node:http:1283:36)
      at Object.handler (node:http:1301:14)
      at handleHttp (ext:sb_core_main_js/js/http.js:107:38)
      at eventLoopTick (ext:core/01_core.js:64:7)
```

## To Reproduce

1. The function file:

```ts
import { Server } from 'npm:@hocuspocus/server@latest'

const server = Server.configure({
  port: 8000,
})

server.listen()
```

2. Try to connect to the websocket, for instance via Postman:

![Bildschirmfoto 2024-03-25 um 12 04 52](https://github.com/supabase/edge-runtime/assets/62803839/cf460194-7244-4eec-b2f6-6025f17e9804)

3. The socket disconnects right away and throws a 502.

## Expected behavior

The socket is connecting when using the deno run command of the Deno CLI, but fails on the Supabase edge runtime, both in the hosted and in the local environment.

**Comment by nyannyacha** [comment]
@colin-chadwick 

Yeah, this is an edge-runtime domain issue.

I was a bit worried after merging that PR earlier, so I tested the `npm:ws` package and it failed as expected.

Websocket upgrades via `Deno.upgradeWebSocket` calls within the user worker are supported, but WebSocket upgrades via the node compatibility layer were not properly implemented in the previous initial websocket support PR.

I'll review this issue and fix it soon. 😁

**Comment by colin-chadwick** [comment]
@nyannyacha Thanks for the quick reply. Looking forward to the fix. I think the full WS support will be a great step forward for the edge runtime. 😃

**Comment by nyannyacha** [comment]
Update:

https://github.com/supabase/edge-runtime/assets/46702285/62580180-9ab3-4a79-88ea-af8bd57ccfd5

https://github.com/ueberdosis/hocuspocus/blob/main/packages/server/src/Server.ts#L24-L38
https://github.com/ueberdosis/hocuspocus/blob/main/packages/server/src/Server.ts#L42-L67
