### ISSUE TITLE
Local Edge Functions no longer working after upgrading to supabase CLI v1.153.1

### ISSUE THREAD

**Issue by williamlmao** [supabase/edge-runtime#306]
# Bug report

- [x] I confirm this is a bug with Supabase, not with my own application. 
- [x] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## Describe the bug

Every local supabase edge function is now throwing a 500 and 546 CORS error. This is extremely similar to an issue we saw in production this last week, we received the same kinds of errors suddenly in production. Supabase support confirmed it was an issue on their end - they had a deployment that had a conflict with a small number of packages so it only affected some users. 

After upgrading the CLI, I am getting the same errors all of a sudden (everything was working fine right before upgrading). My suspicion is the same issue is now on my local machine. I'm not finding a way to roll back my supabase CLI version with homebrew, since it seems I need a specific older formula to do so. If anyone has any tips on rolling back to an older CLI version please let me know. 

I tried `supabase stop --no-backup`, deleting all of the supabase related images/containers/volumes from docker, reinstalling the supabase CLI again. None of this works. 

I think the issue has something to do with some of the packages we are using in the edge functions. The one that standout to me are the sentry and opentelemtry packages, as we use these across all of our functions. 

Creating a brand new edge function with `supabase functions new` will run fine. This tells me it is some conflict with our packages.

This issue isn't just isolated to us or these packages, see these threads in your Discord: 
- https://discord.com/channels/839993398554656828/1223255671374483520
- https://discord.com/channels/839993398554656828/1222494508810371182
- https://discord.com/channels/839993398554656828/1225163570912952491
- https://discord.com/channels/839993398554656828/1225185388625264721

My packages below
```
import { Span, Tracer, context, trace } from 'npm:@opentelemetry/api'
import { OTLPTraceExporter } from 'npm:@opentelemetry/exporter-trace-otlp-proto'
import { Resource } from 'npm:@opentelemetry/resources'
import { NodeSDK } from 'npm:@opentelemetry/sdk-node'
import { BatchSpanProcessor } from 'npm:@opentelemetry/sdk-trace-base'
import { SemanticResourceAttributes } from 'npm:@opentelemetry/semantic-conventions'
import * as Sentry from 'https://deno.land/x/sentry@7.84.0/index.mjs'

```

My CLI version is now on v1.153.1

**Comment by williamlmao** [comment]
<img width="1189" alt="localerrors" src="https://github.com/supabase/edge-runtime/assets/55903529/b669dacf-3243-45a3-8f73-87bdd2d4bc77">

**Comment by williamlmao** [comment]
<img width="2037" alt="image" src="https://github.com/supabase/edge-runtime/assets/55903529/50b36294-5495-4185-82b5-5f207cb42e12">

Appears that support confirmed there was a known issue with opentelemetry

**Comment by sweatybridge** [comment]
As a temporary workaround, you can pin an older version of CLI using npm. For eg

```
npx supabase@v1.151.1 help
```

**Comment by williamlmao** [comment]
Hey @sweatybridge - can confirm this fixed it for me! Really appreciate the quick fix. Is there something else you need to do on your end to make it the most up to date version with homebrew? When I try to upgrade via homebrew it's still stuck on v1.153.1

**Comment by williamlmao** [comment]
Got it. thanks @sweatybridge !

**Comment by alexgshaw** [comment]
I'm running into this same problem with the newest version of the CLI:

Supabase CLI: 1.169.8
Deno: 1.40.3

Hot-reloading is not working. When I try to stop supabase local dev, the edge container will not shut down. No matter what I try (docker rm -f, docker kill) I cannot stop this container. I can only stop it if I restart my computer.

**Comment by sweatybridge** [comment]
@alexgshaw could you open a new issue for it? It's likely something wrong with docker internals.

**Comment by alexgshaw** [comment]
@sweatybridge I found an existing issue and left a comment on it.

https://github.com/supabase/cli/issues/247#issuecomment-2143599716
