### ISSUE TITLE
Error loading supabase-js while deploying edge function

### ISSUE THREAD

**Issue by yunpaik** [supabase/edge-runtime#308]
**Describe the bug**
supabase-js fails to load while deploying the edge function. The same edge function was successfully deployed a couple hours ago and this issue suddenly started happening

**To Reproduce**
1. run `supabase functions deploy`
2. I got the following error:
`Download https://esm.sh/@supabase/supabase-js@2
Error: failed to load 'https://esm.sh/@supabase/supabase-js@2': Import 'https://esm.sh/@supabase/supabase-js@2' failed: error sending request for url (https://esm.sh/@supabase/supabase-js@2): error trying to connect: invalid peer certificate: Expired`

**Comment by sweatybridge** [comment]
transferring to edge-runtime since it looks like an internal error

**Comment by yunpaik** [comment]
In case anyone is pulling their hairs off with this issue, I had to upgrade Docker Desktop to the latest version and problem went away :)
