### ISSUE TITLE
Support private EC key signing

### ISSUE THREAD

**Issue by bavjackson** [supabase/edge-runtime#334]
# Bug report

- [ x] I confirm this is a bug with Supabase, not with my own application. 
- [x ] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## Describe the bug

The supabase edge runtime carried over a lack of support for private EC key signing from the deno runtime [issue 18972](https://github.com/denoland/deno/issues/18972). This was fixed in Deno in march via [pr 22914](https://github.com/denoland/deno/pull/22914).

## To Reproduce

https://github.com/bavjackson/deno-example

## Expected behavior

The runtime should support private EC key encryption, as this is used as part of several well used libraries, including 'google-auth-library'.

## Additional context

Applies to several libraries, as shown in the linked Deno issue.

@james-bowers

**Comment by aoztanir** [comment]
When will this be fixed?

**Comment by nyannyacha** [comment]
Hello @bavjackson 😁

The repository you linked to indirectly requires a web push server implementation to reproduce, so I was unable to get it working locally.

However, I have confirmed that this issue has been mitigated in edge runtime v1.54.0+ with a reproducible example using `sshpk` mentioned in the upstream issue, so closing this issue.

Have a great day!

cc @aoztanir
