### ISSUE TITLE
Latest version of Oak (> 14.1.1) doesn't work on Edge Runtime

### ISSUE THREAD

**Issue by laktek** [supabase/edge-runtime#335]
# Bug report

The following code would not run on Edge Runtime and causes the request to be timed out.

```
import {
  Application,
  isHttpError,
  Router,
} from "https://deno.land/x/oak/mod.ts";

const app = new Application();
const router = new Router();

router.post("/oak-bug/test", async (ctx) => {
  console.log("Hello from Functions!");
  ctx.response.body = "test";
});

app.use(router.routes());
app.use(router.allowedMethods());

await app.listen({ port: 8000 });
```

It looks like the latest versions of Oak are downloaded from JSR, which might be causing this issue. 

If you modify the import URL to `https://deno.land/x/oak@v14.1.1/mod.ts` it will work.

**Comment by nyannyacha** [comment]
IMHO, It could be an ssl handshake issue caused by the forced redirection of the `deno.land` domain to `jsr.io` (not sure).
