### ISSUE TITLE
Update Deno Runtime so that local and deployed version matches

### ISSUE THREAD

**Issue by hyldmo** [supabase/edge-runtime#355]
# Chore

Update Deno Runtime so that local and deployed version matches, or allow updating it manually

## Describe the chore

In https://github.com/supabase/cli/issues/490#issuecomment-1263104657, it mentioned that Deno Deploy always uses the latest version (`1.44` i think is what my live functions are running at). 

While in this repo I see the version is pinned to `v1.40.3`. This breaks my runs locally due to this issue: https://github.com/denoland/deno/issues/22109, which is fixed in the latest version. 

## Additional Context
I'm using `supabase@^1.172.2`, which seems to use `supabase-edge-runtime-1.53.0`

**Comment by laktek** [comment]
We'll be releasing the 1.43 upgrade to CLI and hosted environment within the next 7 days.

**Comment by laktek** [comment]
Deno 1.43 upgrade was released https://github.com/orgs/supabase/discussions/27349
