### ISSUE TITLE
After upgrading supabase i get a _computedKey error

### ISSUE THREAD

**Issue by tonypee** [supabase/edge-runtime#357]
# Bug report

Similar to: https://github.com/supabase/supabase/issues/27108. Open AI library causes issues due to the older version of deno used

When hitting my edge function i get the following error:
```
../wowzer-utopia-one [develop|✚6…2] ❯❯❯ supabase functions serve
Setting up Edge Functions runtime...
Serving functions on http://127.0.0.1:54321/functions/v1/<function-name>
Using supabase-edge-runtime-1.53.3 (compatible with Deno v1.40.3)
serving the request with /home/deno/functions/generate
runtime has escaped from the event loop unexpectedly: event loop error: ReferenceError: _computedKey is not defined
    at https://deno.land/x/openai@v4.26.0/lib/ChatCompletionStream.ts:4:14
failed to send request to user worker: event loop error: ReferenceError: _computedKey is not defined
    at https://deno.land/x/openai@v4.26.0/lib/ChatCompletionStream.ts:4:14
user worker failed to respond: event loop error: ReferenceError: _computedKey is not defined
    at https://deno.land/x/openai@v4.26.0/lib/ChatCompletionStream.ts:4:14
InvalidWorkerResponse: event loop error: ReferenceError: _computedKey is not defined
    at https://deno.land/x/openai@v4.26.0/lib/ChatCompletionStream.ts:4:14
    at async Promise.allSettled (index 1)
    at async UserWorker.fetch (ext:sb_user_workers/user_workers.js:77:21)
    at async Object.handler (file:///home/deno/main/index.ts:171:14)
    at async respond (ext:sb_core_main_js/js/http.js:162:14) {
  name: "InvalidWorkerResponse"
```

-->

- [x] I confirm this is a bug with Supabase, not with my own application. 
- [x] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## Describe the bug

When using OpenAI the code fails. This is apparent in our application code, and in the examples. It seems due to issues in the older version of deno used by supabase edge function runtime - as per the thread https://github.com/nberlette/deno_fmt/issues/2

## To Reproduce

Follow steps in https://supabase.com/docs/guides/ai/examples/openai
Serve the edge function locally
Make the POST request as described in the guide

## System information

- OS: [e.g. macOS, Windows]
- Browser (if applies) [e.g. chrome, safari]
- Version of supabase-js: [e.g. 6.0.2]
- Version of Node.js: [e.g. 10.10.0]

**Comment by nyannyacha** [comment]
Hello @tonypee 😁

This is an upstream issue.
It will resolve when the ongoing Deno codebase version up [PR](https://github.com/supabase/edge-runtime/pull/352) has been merged.

**Comment by tonypee** [comment]
Yup - looks like a dup of https://github.com/supabase/edge-runtime/issues/355 anyway - ill close. thanks
