### ISSUE TITLE
Edge-runtime latest version missing from AWS ECR

### ISSUE THREAD

**Issue by chreds** [supabase/edge-runtime#358]
## Describe the bug

When running supabase functions deploy [function] I get:
```
failed to pull docker image: Error response from daemon: Get "https://public.ecr.aws/v2/": net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)
Retrying after 4s: public.ecr.aws/supabase/edge-runtime:v1.53.3
```

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Remove all existing docker images/containers for supabase
2. Install supabase cli 1.176.4
3. Try to deploy cloud function

## Expected behavior

Should download required docker container from ECR

## System information

- OS: Windows 11
- Supabase CLI 1.176.4 (tried 1.172.2 as well)

**Comment by chreds** [comment]
Was able to resolve. Updated docker and it's working now. Must have been something wonky with the network config or something.

**Comment by laktek** [comment]
@chreds Glad to hear the issue was resolved.
