### ISSUE TITLE
Enabling analytics cause supabase functions deploy to fail.

### ISSUE THREAD

**Issue by ardabeyazoglu** [supabase/edge-runtime#385]
# Bug report

- [x] I confirm this is a bug with Supabase, not with my own application. 
- [x] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## Describe the bug

Deploying supabase functions fail with following error, when [analytics] section in config.toml enabled. 

`failed to start docker container: Error response from daemon: failed to create task for container: failed to initialize logging driver: dial tcp 127.0.0.1:54328: connect: connection refused
`

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Add the following lines to config.toml and try to deploy a function.
```
[analytics]
enabled = true
port = 54327
vector_port = 54328
backend = "postgres"
```

2. Then set enabled to false, and try again. This time it should work.

## Expected behavior

It must work with analytics enabled, because **we need analytics in local supabase runtime for logging to work**.

## System information

- OS: Windows 11
- Version of supabase-js: 1.178.2
- Version of Node.js: v20.15.0

## Additional context

Reported in #378 for github-actions as well. However, I also have the problem in my local windows machine.

**Comment by nyannyacha** [comment]
Hello @ardabeyazoglu 😁

Unfortunately, this issue does not appear to be caused by the edge runtime.

Will transfer the issue to the CLI repository.

**Comment by ardabeyazoglu** [comment]
Hi @nyannyacha , ok i will do it.
