### ISSUE TITLE
InvalidWorkerCreation: worker boot error: failed to create the graph

### ISSUE THREAD

**Issue by gianmarcocalbi** [supabase/edge-runtime#410]
# Bug report

- [x] I confirm this is a bug with Supabase, not with my own application.
- [x] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## Describe the bug

When I serve a function locally that imports a file outside `/supabase/functions` I get the error: 

```
{"code":"BOOT_ERROR","message":"Worker failed to boot (please check logs)"}
```

**The error does not occur when launching the function with** `$ deno run`.

### Logs

```
serving the request with ***/supabase/functions/hello-world
failed to create the graph
An error has occured
InvalidWorkerCreation: worker boot error: failed to create the graph
    at async UserWorker.create (ext:sb_user_workers/user_workers.js:145:15)
    at async Object.handler (file:///root/index.ts:154:22)
    at async respond (ext:sb_core_main_js/js/http.js:163:14) {
  name: "InvalidWorkerCreation"
}
```

## Reproduce steps

1. `$ supabase functions new hello-world`
2. Replace `hello-world/index.ts` with:
    ```typescript
	// @deno-types="npm:@types/express@4.17.15"
	import express, { Request, Response } from 'npm:express@4.21.0';
	import { hello } from '../../../lib.ts';
	
	const app = express();
	app.use(express.json());
	
	const port = 3000;
	
	app.get('/hello-world', (_: Request, res: Response) => {
	  res.send(hello());
	});
	
	app.listen(port, () => {});
	```
3. create a file `lib.ts` in the project root containing the following:
	```typescript
	export function hello() : string {
	  return 'Hello World!';
	}
	```
4. run the function with supabase:
	`$ supabase functions serve hello-world --no-verify-jwt`
	the error occurs
5. run the function with deno (from within the `/supabase/functions/hello-world` folder):
	`$ deno run -A index.ts`
	no issues

**Comment by nyannyacha** [comment]
This issue seems to be caused by the CLI only mounting the /supabase/functions directory that exists on the host machine into the edge runtime container.
From the container's perspective, it looks like no files exist in the parent directory, and as a result, `lib.ts` fails to load.

```jsonc
// docker inspect <edge runtime container id>
...
"Mounts": [
    {
        "Type": "volume",
        "Name": "supabase_edge_runtime_cli",
        "Source": "/var/lib/docker/volumes/supabase_edge_runtime_cli/_data",
        "Destination": "/root/.cache/deno",
        "Driver": "local",
        "Mode": "rw",
        "RW": true,
        "Propagation": ""
    },
    {
        "Type": "bind",
        "Source": "/Users/nyan/Documents/repository/cli/supabase/functions",
        "Destination": "/Users/nyan/Documents/repository/cli/supabase/functions",
        "Mode": "ro",
        "RW": false,
        "Propagation": "rprivate"
    }
],
...
```

```
serving the request with ***/supabase/functions/hello-world
failed to create the graph
An error has occured
```

And simply exposing a `failed to create the graph` message seems problematic.
We actually have a source about why the graph failed to be created for some reason, but we don't render it to the console or in the response.

Regarding the mount issue you're having, there's nothing the edge runtime can do to fix it, but the error message needs improvement, so I'll be submitting a PR soon.

**Comment by nyannyacha** [comment]
Yeah, it should because `supabase/functions` is the mount point of its container. All subpaths for this path should be recognizable from edge runtime.

**Comment by codinronan** [comment]
@nyannyacha any suggestions on debugging this error until such time as an update to the edge-runtime container is released? I am running into this, have gone through every single file (of over 1000, painful) and every single one has imports that are either in the imports list in deno.jsonc, or are contained within the `supabase/functions` folder. So I need to see what the actual resolver error is but I can't figure it out. Any tips?

**Comment by nyannyacha** [comment]
Well...it's complicated, but it's possible...if you're good with Docker.

Finding the file in issue is possible with strace.
You can access the shell of a container running edge runtime via `docker exec -it <edge runtime container id> /bin/bash`.

From there, you need to install the necessary packages for tracing by typing `apt-get update && apt-get install -y htop strace`.

You should be able to find the pid of the edge runtime using htop, which will allow you to observe the syscalls that the edge runtime is calling in real-time via strace.

<img width="1886" alt="스크린샷 2024-09-25 오전 10 06 28" src="https://github.com/user-attachments/assets/22bfdbe3-f2c8-4538-a70d-7f86b216ac18">

After you type strace, as shown below, the shell will log syscalls until you press Ctrl+C.
<img width="1886" alt="스크린샷 2024-09-25 오전 10 07 54" src="https://github.com/user-attachments/assets/96c45114-f63d-42b2-a8cc-6237ae8064dd">

Now send a request and observe the logs that are written to the shell.
If you've followed these instructions well, you should have a syscall logged in your shell that failed to open the file, like this.

<img width="1886" alt="스크린샷 2024-09-25 오전 10 12 38" src="https://github.com/user-attachments/assets/98ef74b2-0446-4889-8e7d-c2e4bd8f99b4">

I hope you find these instructions helpful.
Have a great day!

**Comment by codinronan** [comment]
@nyannyacha Thank you I will give that a try!

**Comment by codinronan** [comment]
@nyannyacha I was able to successfully execute the steps above, however it turned out my error wasn't a missing file, it was the following deno error:

![image](https://github.com/user-attachments/assets/938ead24-4a3e-4263-a04b-d80d2a2934a9)

You'll note in the image it seems you've done some work to spit out the real error :) So it's nice to see that now, but for yesterday, that's what I was running into, across several imports in fact. 

Some needed to be re-spec'd in the import_map.json file (removed the slashes and replaced with dashes) so it wouldn't think they were paths, and I also needed to add the `--import-map` cli parameter to most of my commands. 

Clearly some pretty deep deno changes going on here. I can imagine it's been rough for you guys keeping up with them. I'm glad the supabase cli provides these breakouts like the `--import-map` parameter to fix things otherwise we'd be pretty screwed.

**Comment by nyannyacha** [comment]
Yeah in such a case like yours, the syscall log would look normal, so the method I suggested instructions above would not have been able to resolve the issue.

There are many other cases where a graph error is emitted besides the file not being found, so I will submit a patch in the near future to expose the detailed error.

**Comment by onyedikachi23** [comment]
> This issue seems to be caused by the CLI only mounting the /supabase/functions directory that exists on the host machine into the edge runtime container. From the container's perspective, it looks like no files exist in the parent directory, and as a result, `lib.ts` fails to load.
> 
> ```js
> // docker inspect <edge runtime container id>
> ...
> "Mounts": [
>     {
>         "Type": "volume",
>         "Name": "supabase_edge_runtime_cli",
>         "Source": "/var/lib/docker/volumes/supabase_edge_runtime_cli/_data",
>         "Destination": "/root/.cache/deno",
>         "Driver": "local",
>         "Mode": "rw",
>         "RW": true,
>         "Propagation": ""
>     },
>     {
>         "Type": "bind",
>         "Source": "/Users/nyan/Documents/repository/cli/supabase/functions",
>         "Destination": "/Users/nyan/Documents/repository/cli/supabase/functions",
>         "Mode": "ro",
>         "RW": false,
>         "Propagation": "rprivate"
>     }
> ],
> ...
> ```
> 
> ```
> serving the request with ***/supabase/functions/hello-world
> failed to create the graph
> An error has occured
> ```
> 
> And simply exposing a `failed to create the graph` message seems problematic. We actually have a source about why the graph failed to be created for some reason, but we didn't render it to the console or in the response.
> 
> Regarding the mount issue you're having, there's nothing the edge runtime can do to fix it, but the error message needs improvement, so I'll be submitting a PR soon.
> 
> --
> 
> Error message should be able to be improved as follows:
> 
> Response
> 
> ```
> {
>     "msg": "InvalidWorkerCreation: worker boot error: failed to create the graph: Module not found \"file:///workspaces/lib.ts\".\n    at file:///workspaces/edge-runtime/examples/serve/index.ts:3:23"
> }
> ```
> 
> Console
> 
> ```
> worker boot error: failed to create the graph: Module not found "file:///workspaces/lib.ts".
>     at file:///workspaces/edge-runtime/examples/serve/index.ts:3:23    
> InvalidWorkerCreation: worker boot error: failed to create the graph: Module not found "file:///workspaces/lib.ts".
>     at file:///workspaces/edge-runtime/examples/serve/index.ts:3:23
>     at async UserWorker.create (ext:sb_user_workers/user_workers.js:145:15)
>     at async createWorker (file:///workspaces/edge-runtime/examples/main/index.ts:85:12)
>     at async callWorker (file:///workspaces/edge-runtime/examples/main/index.ts:103:22)
>     at async respond (ext:sb_core_main_js/js/http.js:163:14) {
>   name: "InvalidWorkerCreation"
> }
> ```

@nyannyacha I'm having a very similar problem here, but I'm not using an Express server.

This is sub-directory setup under my supabase directory:

![vscode screenshot](https://github.com/user-attachments/assets/c9c44e0c-e88f-4cf0-9b94-fa24ab5b87a9)


I don't really know how Deno and Docker works and from this reply I qouted, I don't know where to start debugging, so I might have to paste the codes in the sub directories here:

- In `/_utils` I have `stripe.ts`:

```typescript
	
	 // esm.sh is used to compile stripe-node to be compatible with ES modules.
import Stripe from 'https://esm.sh/stripe@16.12.0?target=deno&deno-std=0.132.0&no-check';

export const stripe = Stripe(Deno.env.get('STRIPE_SECRET_KEY') ?? '', {
  httpClient: Stripe.createFetchHttpClient(),
});import { get } from 'react-native/Libraries/TurboModule/TurboModuleRegistry';

```

- in `/payment-sheet` I have `index.ts`:

```typescript

// Follow this setup guide to integrate the Deno language server with your editor:
// https://deno.land/manual/getting_started/setup_your_environment
// This enables autocomplete, go to definition, etc.

// Setup type definitions for built-in Supabase Runtime APIs 
import "jsr:@supabase/functions-js/edge-runtime.d.ts";
import { stripe } from "../_utils/stripe.ts";

console.log("Hello from Functions!");

Deno.serve(async (req) => {

  try {
    const { amount } = await req.json();

  const paymentIntent = await stripe.paymentIntents.create({
    amount: 1099,
    currency: "usd"
  });
    console.log(paymentIntent);
    

  const res = {
    paymentIntent: paymentIntent.client_secret,
    publishabledKey: Deno.env.get("EXPO_PUBLIC_STRIPE_PUBLISHABLE_KEY")
  };

 

  return new Response(
    JSON.stringify(res), 
    { headers: { "Content-Type": "application/json" } },
  );
    
  } catch (error) {
    console.log(error);
    
    return new Response(JSON.stringify(error), {
      headers: { "Content-Type": "application/json" },
      status: 400,
    })
  }


  
});

/* To invoke locally:

  1. Run `supabase start` (see: https://supabase.com/docs/reference/cli/supabase-start)
  2. Make an HTTP request:

  */

  /* curl -i --location --request POST 'http://127.0.0.1:54321/functions/v1/payment-sheet' \
    --header 'Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZS1kZW1vIiwicm9sZSI6ImFub24iLCJleHAiOjE5ODM4MTI5OTZ9.CRXP1A7WOeoJeXxjNni43kdQwgnWNReilDMblYTn_I0' \
    --header 'Content-Type: application/json' \
    --data '{"amount":1150}'
 */

```

You can see the `curl` command I'm using thats giving the error whenever I run it.

For further info, I'm following a tutorial, heres the GitHub repo: [food-ordering-app](https://github.com/notJust-dev/FoodOrdering)

**Comment by codinronan** [comment]
@onyedikachi23 have you also run `supabase functions serve` from inside your `src` directory? (looks like src from your screenshot, has to be one folder above the supabase folder).

**Comment by onyedikachi23** [comment]
@codinronan 
I run the command from the root directory (and yes, `/src` is one level above the `/supabase`):

```bash

npx supabase functions serve --env-file .env payment-sheet

```

**Comment by hitamu** [comment]
I'm facing the same issue. Previously it was working fine until I change my folder name of the edge function

**Comment by onyedikachi23** [comment]
@hitamu  can I how your setup was when it was working fine? I need to try and see if that helps me out.

**Comment by junedkhatri31** [comment]
How to use version 1.58.11 in local supabase?

**Comment by codinronan** [comment]
> How to use version 1.58.11 in local supabase?

I don't think it's possible without action from the supabase team to make it available in the cli, but hoping I'm wrong and they reply because I'd like to try it as well.

**Comment by junedkhatri31** [comment]
@codinronan I built my own cli from source - https://github.com/supabase/cli/

**Comment by nyannyacha** [comment]
@junedkhatri31 
@codinronan 

https://github.com/supabase/cli/releases/tag/v1.202.3
😋

**Comment by onyedikachi23** [comment]
How do I update the **Supabase Edge Runtime** in the Expo project?

I'm following this guide at [*supabase/edge-runtime*](https://github.com/supabase/edge-runtime/pkgs/container/edge-runtime) , so is running this enough:

```bash

docker pull ghcr.io/supabase/edge-runtime:v1.58.11

```

**Comment by fabiendeborde** [comment]
Sorry to reopen this topic, but I am having the same message:
```
worker boot error: failed to create the graph: Relative import path "drizzle-orm/postgres-js" not prefixed with / or ./ or ../ and not in import map from "file:///Users/**/**/supabase/functions/api/libs/database.ts"
```
I had a few errors with Hono, dayjs and others too.
Every packages using a slash in its name fails with Supabase CLI, but resolve normally with Deno when called directly.

I updated the `imports` in the `deno.json` and it is working fine now.
```ts
"hono": "npm:hono@^4.9.2",
"hono/cookie": "npm:hono@^4.9.2/cookie",
```

I am new to Supabase and Deno so it may be normal, but it took me some time to realize how to solve this.
Hope this helps someone later on.

**Comment by nyannyacha** [comment]
Hello @fabiendeborde 😋

Can you please open a new issue with a reproducible code/repository?
If you ask a question in an issue that was closed a long time ago, it may not get the maintainer's attention.

**Comment by Ge6ben** [comment]
The issue happens when running:

`deno cache --reload index.ts`

This command causes the error.

To fix it, please reinstall Deno completely and install it again without running the cache command.
In other words, after reinstalling Deno, do not run:

`deno cache --reload index.ts`

**Comment by idolize** [comment]
@Ge6ben can you elaborate on why this is? I'm facing the same issue currently and reinstalling deno did not fix the issue.

Edit: I tried everything I could think of (restarting computer, reinstalling deno, reinstalling supabase CLI, deno clean, changing deno.json relative imports like [fabiendeborde](https://github.com/fabiendeborde) suggested) but nothing worked.

Then Claude suggested adding the `--use-api` argument and that seemed to work!
