### ISSUE TITLE
`--static` flag cannot be used multiple times

### ISSUE THREAD

**Issue by djalmajr** [supabase/edge-runtime#431]
Hello everyone. I'm having trouble sending multiple extensions in the `--static` argument using the examples provided here. Could someone please assist me with this?

How can I support multiple extensions? For example:

`edge_runtime start --main-service ./examples/main --static "./examples/**/*.{txt,json,yaml}"`

Unfortunately, this doesn't work. This doesn't work either:

`edge_runtime start --main-service ./examples/main --static "./examples/**/*.txt" --static "./examples/**/*.json"`

It gives me:

`error: the argument '--static <Path>' cannot be used multiple times`

**Comment by nyannyacha** [comment]
Hello @djalmajr 😁

This is a bug.
Will be submitting a PR for this soon.

Thanks for reporting!
