### ISSUE TITLE
TypeError: cannot read headers: request closed

### ISSUE THREAD

**Issue by shivamklr** [supabase/edge-runtime#435]
# Bug report

- [x] I confirm this is a bug with Supabase, not with my own application. 
- [x] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## Describe the bug

I am getting this TypeError when I try to access the headers in the request. Moreover, even after trying the example shared by the team at [telegram bot example,](https://github.com/supabase/supabase/tree/master/examples/edge-functions/supabase/functions/telegram-bot), when deployed it still gives me the same issue.
Not only that, but the bot **deployed by the supabase team** [supabase_example_bot](https://t.me/supabase_example_bot) also does not reply, which I suspect has same errors in the supabase edge functions.

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Follow instructions in the example code mentioned above.
2. Call the bot from Telegram

## Expected behavior

1. The commands should execute on the Edge without any errors.

**Comment by shivamklr** [comment]
Refer to the full logs here
https://github.com/supabase/supabase/issues/30131

**Comment by shivamklr** [comment]
And btw, I tried running the same script with `deno run ...` directly, and it is working perfectly.
I am on `Deno 2.0.4` locally if that matters.

**Comment by silentworks** [comment]
I've tested this following the instructions provided in the example telegram bot and haven't had any issues. I'm unable to replicate the one mentioned here.

**Comment by shivamklr** [comment]
Got the issue. This looks unrelated to edge runtime. Let me get

**Comment by shivamklr** [comment]
There is a long thread about this on grammY. Here is a link to the fix that worked for me.
https://github.com/grammyjs/grammY/issues/350#issuecomment-2457156001
