### ISSUE TITLE
Can we set cpu hard limit from env ?please

### ISSUE THREAD

**Issue by boyhax** [supabase/edge-runtime#441]
https://github.com/supabase/edge-runtime/blob/1bb7f70bc9a9f4312ca3bbe5d249157ad5da13a8/crates/base/src/deno_runtime.rs#L1922

My fcm notification function not working because if cpu hard limit .it need 2.5 sec .my server is slow and the function is same as offical one and also tried to change to different ways but still will need more than 200 ms .

**Comment by nyannyacha** [comment]
Close this issue, as it duplicates #321. (Myself and someone else posted how to change the cpu time limit in that issue, so you can check it out)

Changing the cpu time limit via envs is not provided by default, but you can freely access the host system envs using `Deno.env` in the main worker script and use it to set the cpu time limit.
