### ISSUE TITLE
Unable to inspect worker: "worker boot error: Uncaught SyntaxError: Unexpected non-whitespace character after JSON"

### ISSUE THREAD

**Issue by 0x5457** [supabase/edge-runtime#456]
# Bug report

- [x] I confirm this is a bug with Supabase, not with my own application. 
- [x] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## Describe the bug

If I start the main worker with `--inspect-main` `--inspect-brk` args and import the json file in the main worker code, the following error will occur

```sh
2024-12-02T10:52:42.988080Z ERROR ThreadId(03) base::rt_worker::implementation::default_handler: worker boot error: Uncaught SyntaxError: Unexpected non-whitespace character after JSON at position 574 (line 20 column 1)    
Error: main worker boot error: worker boot error
```

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

main worker code:
```typescript
import { STATUS_CODE } from "jsr:@std/http";
console.log(STATUS_CODE.Accepted);
```
run edge-runtime with `--inspect-main` and `--inspect-brk`
```sh
./target/debug/edge-runtime "$@" start \
    --inspect-main \
    --inspect-brk \
    --main-service ./test-main
```

## Expected behavior
The main worker runs normally and waits for debugging to start

## Screenshots
<img width="1032" alt="image" src="https://github.com/user-attachments/assets/4e20c6ba-aac4-4d7c-be17-72d00f527443">

## System information

- OS: macOS

## Additional context

The reason for the error may be that the inline sourcemap is added to the json file here:
https://github.com/supabase/edge-runtime/blob/5707665873fee6938a84c3a56007cdabaf75b9c8/crates/sb_module_loader/standalone/standalone_module_loader.rs#L264-L265

**Comment by Codexiaoyi** [comment]
same issue!

**Comment by nyannyacha** [comment]
I will look into it shortly 😋
