### ISSUE TITLE
Isolate Halting exit code is not properly sent to parent channel

### ISSUE THREAD

**Issue by andreespirela** [supabase/edge-runtime#58]
# Bug report
We're probably not sending the correct exit codes for `EdgeTimeResult` because this errors. Might be part of a *potential* race condition

edge_runtime.rs#L334 errors
```
            if halt_isolate_tx.send(call).is_err() {
                error!("failed to send the halt execution signal");
            }
```
<img width="355" alt="image" src="https://user-images.githubusercontent.com/60560109/233132546-1fe89f56-e25f-4c2d-aa46-794e690ba9db.png">

**Comment by laktek** [comment]
This should be fixed with #123
