### ISSUE TITLE
Latest oak server causing edge runtime to throw an error

### ISSUE THREAD

**Issue by silentworks** [supabase/edge-runtime#60]
# Bug report

- [x] I confirm this is a bug with Supabase, not with my own application. 
- [x] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## Describe the bug

When using the latest (v12.2.0 at the time of writing) oak server in the edge runtime it throw an error about `worker thread panicked TypeError: Cannot read properties of undefined (reading 'querySync'). However if you should explicitly state the version of oak and use the previous version v12.1.0 this error goes away and the endpoints work as intended.

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Deploy the [self-hosted-edge-functions-demo](https://github.com/supabase/self-hosted-edge-functions-demo) to fly.io or any hosting provider
2. Make a request to any of the oak server's endpoints
3. Check the console where you deployed the project to see the error

## Expected behavior

No errors, it should just work.

## Screenshots

![Screenshot 2023-04-21 004010](https://user-images.githubusercontent.com/79497/233516653-df68df7b-e455-45c7-b8ff-0bd77f52dff3.png)

## System information

- OS: Windows 11
- Browser (if applies) [e.g. chrome, safari]
- Version of edge-runtime: v1.2.14

**Comment by laktek** [comment]
Looks like we may need to expose `Deno.permissions` global object. `querySync` is a property of it.

**Comment by andreespirela** [comment]
<img width="245" alt="image" src="https://user-images.githubusercontent.com/60560109/234111754-daa4ea99-4bec-437f-8c7d-78f4230b00ba.png">
<img width="1443" alt="image" src="https://user-images.githubusercontent.com/60560109/234111795-1f4a3fff-4fa9-4c62-bdc2-d6347ba85f84.png">

/greet
<img width="1320" alt="image" src="https://user-images.githubusercontent.com/60560109/234111998-d2f5cd49-afe5-42bf-b50e-2b73d94687c1.png">

**Comment by andreespirela** [comment]
Seems as mentioned above, it only happens with v12.2.0

**Comment by andreespirela** [comment]
@laktek Fixed this bug, will open a PR. Needs some discussion & trying to write some tests, lil tricky.

**Comment by andreespirela** [comment]
Fixed in #64 .
