### ISSUE TITLE
README diagram has gone full camo in dark theme :(

### ISSUE THREAD

**Issue by soonann** [supabase/edge-runtime#61]
Love the diagram on the README, but it seems like it has a transparent background which doesn't work well with the dark theme
![image](https://user-images.githubusercontent.com/31432464/233561478-7e4da58a-1722-40d1-9ccb-b2a1a4e2a1ca.png)

I just faced this issue myself the other day and I tired to add a style tag to the image, but apparently github strips off any style tags when rendering the image
https://github.com/orgs/community/discussions/41899

So instead, I added a `style` tag in my svg since they support style tags. Something like `<svg style='background-color:white' ..... >`

I have a fix for it that introduces the above, so do leme know if its ok for me to send in a PR (or if you would like a different fix)
https://github.com/soonann/edge-runtime/tree/fix-edge-diagram

**Comment by laktek** [comment]
@soonann Good catch and a smart solution! Can you open a PR please?
