### ISSUE TITLE
examples/opengraph do not get connection

### ISSUE THREAD

**Issue by zhenfeng-zhu** [supabase/edge-runtime#66]
# Bug report

```
 ~/github/supabase/edge-runtime/ [fix/opengraph*] cargo run -- start --main-service  ./examples/opengraph
    Finished dev [unoptimized + debuginfo] target(s) in 0.34s
     Running `target/debug/edge-runtime start --main-service ./examples/opengraph`
Listening on http://localhost:8000/
```

But it can't be connected on 8000

**Comment by andreespirela** [comment]
Can't reproduce on latest main. @laktek 
<img width="1724" alt="image" src="https://user-images.githubusercontent.com/60560109/234607812-85130e8d-c37c-48d8-b6ad-71757b05e2c2.png">

**Comment by laktek** [comment]
@zhenfeng-zhu seems like you're trying to run the `opengraph` as the main service. Instead try running `/examples/main` as the main and then access `localhost:8000/opengraph`.

**Comment by zhenfeng-zhu** [comment]
Got it! Thanks for your helping.
