### ISSUE TITLE
import npm module fail

### ISSUE THREAD

**Issue by okxiaoliang4** [supabase/edge-runtime#78]
# Bug report

- [ ] I confirm this is a bug with Supabase, not with my own application. 
- [x] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## Describe the bug

```sh
2023-05-01 15:54:13 worker thread panicked Unsupported scheme "npm" for module "npm:ali-oss@6.17.1". Supported schemes: [
2023-05-01 15:54:13     "data",
2023-05-01 15:54:13     "blob",
2023-05-01 15:54:13     "file",
2023-05-01 15:54:13     "http",
2023-05-01 15:54:13     "https",
2023-05-01 15:54:13 ]
```

## To Reproduce

```typescript
import OSS from "npm:ali-oss@6.17.1";
```

## Expected behavior

import npm module successful

## Screenshots

<img width="1088" alt="image" src="https://user-images.githubusercontent.com/22525904/235426111-337d765f-9754-4458-93c7-5fa4ac67cbad.png">

## System information

- MacOS
- Edge
- supabase-js: 2.21.0
- Node.js: v18.14.0

**Comment by mindblight** [comment]
I'm running into the same issue. Some of the `esm.sh` files aren't working due to incorrect node polyfills. I'm hoping that importing the "official" way would be a workaround, but I'm hitting the same problem with the edge functions

**Comment by zdanl** [comment]
I'm trying to import `https://esm.sh/ethers@6.4.1` and create an Ethereum wallet by calling `const wallet = ethers.Wallet.createRandom()` in an Edge Function, but despite near instant deployment time, I get an Internal Server Error:

`TypeError: Expected instance of class which extends utils.Hash
    at new E (https://esm.sh/v124/@noble/hashes@1.1.2/deno/pbkdf2.js:2:2102)
    at Function.H.create (https://esm.sh/v124/@noble/hashes@1.1.2/deno/pbkdf2.js:2:3177)
    at O (https://esm.sh/v124/@noble/hashes@1.1.2/deno/pbkdf2.js:2:3423)
    at X (https://esm.sh/v124/@noble/hashes@1.1.2/deno/pbkdf2.js:2:3653)
    at go (https://esm.sh/v124/ethers@6.4.1/deno/ethers.mjs:2:34498)
    at vo (https://esm.sh/v124/ethers@6.4.1/deno/ethers.mjs:2:35665)
    at mt (https://esm.sh/v124/ethers@6.4.1/deno/ethers.mjs:2:35754)
    at Ft.computeSeed (https://esm.sh/v124/ethers@6.4.1/deno/ethers.mjs:5:7795)
    at Function.createRandom (https://esm.sh/v124/ethers@6.4.1/deno/ethers.mjs:5:17213)
    at Function.createRandom (https://esm.sh/v124/ethers@6.4.1/deno/ethers.mjs:5:20684)
`

It works fine locally.

**Comment by chingiz** [comment]
I am having the same problem. Everything works locally by running `deno run index.ts`

**Comment by Pictor13** [comment]
Mmmh, am I hallucinating or actually Supabase mentioned recently that they (at least for now) dropped the NPM support flag from Deno?

You can [see in this other issue of mine](https://github.com/supabase/supabase/issues/15040#issuecomment-1592249011) that (inside local-dev docker created by `supabase start`) the Deno CLI is being called with the `--no-npm` option.

I think you'll have to focus on figuring out how to correctly fetch dependencies from `esm.sh` (or another [Deno-friendly CDN](https://deno.com/manual@v1.12.2/npm_nodejs/cdns#deno-friendly-cdns)).

**Comment by chief-nerd** [comment]
Waiting for npm support -- for Firebase Cloud Messaging (Notifications) ... kinda a big missing thing. :/

**Comment by chief-nerd** [comment]
@Pictor13 you mean this comment here from @laktek 
https://github.com/orgs/supabase/discussions/7742#discussioncomment-5375195

NPM support would be such a great thing -- it would eliminate a lot of problems with missing dependencies. 
Should be high priority.

**Comment by barbinbrad** [comment]
+1 for `npm:<package>@<version>` imports.

**Comment by AndersonMamede** [comment]
+1 for adding Deno's native npm support. For now it seems https://github.com/supabase/edge-runtime/issues/82#issuecomment-1548130271 will work to use `firebase-admin` lib

**Comment by Maxim-Filimonov** [comment]
Meanwhile https://deno.com/blog/npm-on-deno-deploy. I thought that supabase edge runtime is based off deno deploy. Does it mean we can expect supabase to add support soon too?

**Comment by Kerren-Entrostat** [comment]
I agree with @Maxim-Filimonov, I think it's a major selling point to support npm modules (in Deno) and that's a major win for Supabase as well!

Hopefully, we'll see this enabled soon!

**Comment by Aadim1** [comment]
https://supabase.com/changelog. I can see here that they are using npm:@supabase.. to import { createClient } so I am guessing its in the work. Is there any timeline? I can continue developing locally for the time being, if its going to be supported soon.

**Comment by laktek** [comment]
Yep, this is currently worked on. I can't provide an accurate an ETA for it as there are few unknowns at the moment. Will post an update when we have some progress.

@Aadim1 unfortunately that example wouldn't work in Supabase edge functions yet :(

**Comment by Aadim1** [comment]
@laktek Thanks for the quick reply. Happy to know its in active development. Cheers.

**Comment by localhosted** [comment]
With the recent [announcement here](https://supabase.com/blog/edge-functions-node-npm), does edge-runtime already support npm modules?

**Comment by laktek** [comment]
yes, importing npm modules with `npm:` specifier is now supported in edge-runtime.

**Comment by ekatzenstein** [comment]
How would this work with a nextjs project? Haven't found anything in the documentation
