### ISSUE TITLE
Channel is closed because worker has previously died

### ISSUE THREAD

**Issue by andreespirela** [supabase/edge-runtime#80]
# Bug report

When a request is received in `main/index.ts`. A worker is created and this one is added to a cache. If the worker and it's only deleted/cleaned when 

```js
    } catch (e) {
      console.error(e);
      if (e.message === "user worker not available") {
        // remove the worker from cache
        workerCache.delete(servicePath);
        // recall the worker
        return callWorker();
      } else {
        const error = { msg: e.toString() }
        return new Response(
            JSON.stringify(error),
            { status: 500, headers: { "Content-Type": "application/json" } },
        );
      }
    }
```

We need to find a better way to clean besides a message `user worker not available` because there have been instances I've run into where the worker dies and it's kept cached, which makes the request unreachable to its target channel

**Comment by eugenever** [comment]
Hello, for myself I temporarily use the following solutions:
```
const createWorker = async () => {
    const memoryLimitMb = 150;    
    const workerTimeoutMs = 1 * 60 * 1000;
    const noModuleCache = false;
    const importMapPath = null;
    const envVarsObj = Deno.env.toObject();
    const envVars = Object.keys(envVarsObj).map(k => [k, envVarsObj[k]]);

    const worker = await EdgeRuntime.userWorkers.create({
        servicePath,
        memoryLimitMb,
        workerTimeoutMs,
        noModuleCache,
        importMapPath,
        envVars
    });
    const nowDate = new Date();
    const expireDate = new Date(nowDate.getTime() + workerTimeoutMs);
    const expireWorker = {
        worker: worker,
        expireDate: expireDate,
    }

    return expireWorker;
}
```
and try block from callWorker
```
try {
      // check if an existing worker is available in cache      
      let expireWorker = workerCache.get(servicePath);      
      if (!expireWorker) {
        expireWorker = await createWorker();
        workerCache.set(servicePath, expireWorker);
      } else {       
        const nowDate = new Date().getTime();
        
        if (expireWorker.expireDate <= nowDate) {
            workerCache.delete(servicePath);        
            
            expireWorker = await createWorker();
            workerCache.set(servicePath, expireWorker);
        }
      }      
      
      const res = await expireWorker.worker.fetch(req);
      return res;
}
```
But the problem remains, for example, the worker receives a request that processes several seconds (long mathematical calculations) and at this moment the worker's lifetime expires, which happens to the thread_safe_handle.terminate_execution() call from start_controller_thread. As a result, the worker ends its work, leaving the request unprocessed.

**Comment by laktek** [comment]
@eugenever Try the latest version of Edge Runtime. The caching/expiring workers are handled within Edge Runtime and main function don't need to cache workers (check the updated [example](https://github.com/supabase/edge-runtime/blob/main/examples/main/index.ts))

Closing this issue.
