### ISSUE TITLE
After restarting project postgresjs can no longer connect `ops.op_set_keepalive is not a function`

### ISSUE THREAD

**Issue by evelant** [supabase/edge-runtime#81]
# Bug report

- [X ] I confirm this is a bug with Supabase, not with my own application. 
- [X ] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## Describe the bug

After restarting project postgresjs can no longer connect, it throws `ops.op_set_keepalive is not a function`. There have been no changes to my code. I only restarted my project via the Supabase dashboard due to an unrelated issue.

It seems that maybe there were some changes to the edge runtime that cause some deno APIs to no longer function correctly?

```
TypeError: ops.op_set_keepalive is not a function
    at TcpConn.setKeepAlive (ext:deno_net/01_net.js:162:16)
   at Object.setKeepAlive (https://deno.land/x/postgresjs@v3.3.4/polyfills.js:37:61)
    at connected (https://deno.land/x/postgresjs@v3.3.4/src/connection.js:365:51)
    at https://deno.land/x/postgresjs@v3.3.4/polyfills.js:150:32
    at Array.forEach (<anonymous>)
    at call (https://deno.land/x/postgresjs@v3.3.4/polyfills.js:150:18)
    at success (https://deno.land/x/postgresjs@v3.3.4/polyfills.js:103:11)
    at eventLoopTick (ext:core/01_core.js:166:11)
    at cachedError (https://deno.land/x/postgresjs@v3.3.4/src/query.js:171:23)
    at new Query (https://deno.land/x/postgresjs@v3.3.4/src/query.js:36:24)
    at sql (https://deno.land/x/postgresjs@v3.3.4/src/index.js:112:11)
    at file:///src/index.ts:153:61"}
```

## To Reproduce

1. Deploy an edge function that connects to the db with postgresjs
2. Observe that connection fails with the above error

## Expected behavior

Code that worked previously should continue to work unless a breaking change has been announced

## System information

- OS: N/A
- Browser (if applies) N/A
- Version of supabase-js: N/A
- Version of Node.js: N/A

## Additional context

N/A

**Comment by laktek** [comment]
@evelant Are you experiencing this issue both locally and after you deploy to production? There seems to be an ongoing Deno Deploy outage that may be the cause of this https://denostatus.com/

**Comment by evelant** [comment]
This issue is only happening in production. My code did not change. This started happening immediately after I restarted my production Supabase instance.The Deno Deploy issue doesn’t appear to be related as far as I can tell. 

I’m not sure how this is possible, but the failure appears to be here https://github.com/denoland/deno/blob/a6c47ee74023f6ef683988cabc8caa95406e3c99/ext/net/01_net.js#L169 where Deno is calling into its native rust code here https://github.com/denoland/deno/blob/a6c47ee74023f6ef683988cabc8caa95406e3c99/ext/net/ops.rs#L673. That’s why I suspect that it could be an issue with Supabase’s custom runtime, but I can’t be certain.

Hopefully we can figure this out, my app is still in a total outage due to this.

Andrew

**Comment by evelant** [comment]
Hmm perhaps it is an issue with Deno Deploy. My staging instance (which was not restarted or changed in any way) is experiencing the same problem.

**Comment by evelant** [comment]
@laktek some more clues here https://github.com/denoland/deploy_feedback/issues/382#issuecomment-1536587625


It appears there may have been a change in Deno Deploy to remove "disabled ops" entirely. It seems they may have silently removed APIs even though existing code was using them.

**Comment by laktek** [comment]
Yep, I got an update from Deno Deploy team that they are rolling out a fix for it.

**Comment by evelant** [comment]
At least as of now it's still down. Did they give any ETA on this fix?

**Comment by laktek** [comment]
Looks like it waa fixed https://github.com/denoland/deploy_feedback/issues/382
