### ISSUE TITLE
ReadableStream as Response.body causes function to stall

### ISSUE THREAD

**Issue by zcei** [supabase/edge-runtime#91]
# Bug report

- [x] I confirm this is a bug with Supabase, not with my own application. 
- [x] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## Describe the bug

With Supabase CLI 1.57.4, the edge-runtime version 1.2.19 was rolled out.
This includes a fix for sending back `null` values in the HTTP 204 status code, which rquired no body to be sent. (See issue https://github.com/supabase/cli/issues/1071 and its fix)

I suspect that with this change, the support for `ReadableStream`s has been broken, as they don't contain a `.size` and thus might be treated incorrectly by the fix.

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Go to https://github.com/zcei/supabase-response-stream-bug
2. Clone repository & setup supabase
3. Serve functions
4. Issue the two requests from the bottom of the README

## Expected behavior

Both requests should work: one serves back a 204 with no content and the other a 200 with the text content of the stream.

## ~Screenshots~

~If applicable, add screenshots to help explain your problem.~

## System information

- OS: macOS
- ~Browser (if applies) [e.g. chrome, safari]~ reproducible with Browsers as with cURL
- Version of supabase-js: 1.58.1
- Version of Node.js: 18.14.1

## Additional context

I suspect that the line to fix it ([see here](https://github.com/supabase/edge-runtime/pull/84/files#diff-3988aa73db0fdfca8e726d9dc95e7ed1f098d4805a0f3f1160d9b2464be25779R52)) does not account for all cases. e.g. I don't think a `ReadableStream` can have a `.size` property when it's not clear yet whether someone will write to that stream.

I was trying to hop through Deno with the debugger, but as this is my first sparring with Deno, sadly to no great success.

Some pointers that may help, or could be red herrings: 

* The 204 requests used to fail with the error that is raised [here](https://github.com/denoland/deno/blob/6bea6b31d3b502165e7e890c889919d67df1a795/ext/fetch/23_response.js#L203)
* This error happens when `bodyWithType` is not null ([see here](https://github.com/denoland/deno/blob/6bea6b31d3b502165e7e890c889919d67df1a795/ext/fetch/23_response.js#L322))
* The `body` is created by hopping through a few layers of `webidl.converters`, which is where I lost track with my current debugger setup 😞 . From looking at the code in GitHub, there's a chance that `converters.DOMString` is called which could return `'null'` rather than `null`.
* Tried to reproduce with plain Deno (without supabase) but the function seems to have worked there. So I'm not sure whether Deno fixed it in their latest version already, or I chased down an incorrect assumption.

**Comment by andreespirela** [comment]
Taking a look
